apiVersion: apps/v1
kind: Deployment
metadata:
  name: cristian-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cristian
  template:
    metadata:
      labels:
        app: cristian
        version: "2.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "32111"
    spec:
      containers:
        - name: cristian
          image: linuxtips/nginx-prometheus-exporter:2.0.0
          env:
            - name: VERSION
              value: "2.0.0"
          ports:
           - containerPort: 80
           - containerPort: 32111
          resources: {}