apiVersion: batch/v1
kind: CronJob
metadata: 
  name: giropops-cron
spec: 
  schedule: "*/1 * * * *"
  jobTemplate:
    spec: 
      template: 
        spec: 
          containers: 
          - name: giropops-cron
            image: busybox
            command: 
            - /bin/sh
            - -c
            - date; echo BemVindo ao Descomplicando Kubernetes - Linuxtips VAII ;sleep 30
          restartPolicy: OnFailure
