apiVersion: v1
kind: Pod
metadata:
  name: busybox-configmap-file
  namespace: default
spec:
  containers:
  - name: busy-configmap
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts: 
    - name: meu-configmap-vol
      mountPath: /etc/frutas
  volumes: 
  - name: meu-configmap-vol
    configMap: 
      name: cores-frutas
