apiVersion: v1
kind: Pod
metadata:
  name: test-secret-env
  namespace: default
spec:
  containers:
  - name: busy-secret-env
    image: busybox
    command:
      - sleep
      - "3600"
    env:
    - name: MEU_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-literal-secret
          key: user
    - name: MEU_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-literal-secret
          key: password
    resources: {}
    